name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup dependencies
        if: runner.os == 'Linux'
        run: sudo apt -qq install libgtk-3-dev
      - run: make
      - name: Build examples
        run: odin build examples/main.odin -file
